# Generated by Django 2.0.5 on 2018-07-28 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auto_20180728_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='host_user_bind',
            field=models.ManyToManyField(blank=True, to='audit.HostUserBind'),
        ),
    ]
