# Generated by Django 2.0.5 on 2018-07-28 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_auto_20180728_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostgroup',
            name='host_user_binds',
            field=models.ManyToManyField(to='audit.HostUserBind'),
        ),
    ]
